name: pmtris
version: '1.0'
summary: Poor Man's Tetris Clone
description: |
  Tetris in the terminal! 
grade: stable 
confinement: strict 

apps:
  pmtris:
    command: python $SNAP/bin/pmtris.py
     
parts: 
  pmtris:
    source: https://github.com/kz6fittycent/pmtris
    source-type: git
    plugin: python
    python-version: python2
    python-packages:
      - numpy
    
    build-packages:
      - python
      
    stage-packages:
      - python

  publish:
    plugin: copy
    files:
      ./pmtris.py: bin/pmtris.py
